### ISSUE TITLE
No third column 'Support (Discont'd)' in .facts

### ISSUE THREAD

**Issue by abenjak** [sahandk/HINTRA#2]
Hello,

Thank you for the nice tool.
According to the manual there should be a third column 'Support (Discont'd)' in the .facts output, but this is not the case.

Best,
Andrej

**Comment by sahandk** [comment]
Hello Andrej,

Thank you for the feedback!

That column was redundant and the information could be easily computed using the other columns. So, the manual is updated to be consistent with the actual tool outputs.

Best,
Sahand
